Review tf activity type
linked-statistics/COOS pull request #100
Opened 2022-10-11 14:48 UTC by flo7894

2022-10-11 20:13 UTC, tfrancart commented on coos.ttl
> +<http://id.unece.org/activities/officialStatistics> a coos:ActivityCategory ;
Il faudrait ajouter explicitement le type skos:Concept - même si on en hérite, c'est mieux de l'expliciter pour compatibilité avec tous les outils SKOS

2022-10-11 20:13 UTC, tfrancart commented on coos.ttl
> +<http://id.unece.org/activities/officialStatistics> a coos:ActivityCategory ;
(a faire partout, en plus de coos:ActivityCategory)

2022-10-11 20:14 UTC, tfrancart requested changes
Ajouter explicitement le type skos:Concept en plus de coos:ActivityCategory

2022-10-12 07:06 UTC, tfrancart approved these changes

2022-10-12 18:04 UTC, FlavioRizzolo approved these changes

2022-10-13 07:05 UTC, FranckCo approved these changes

2022-10-13 07:07 UTC, merged